services:
  node:
    build:
      context: ../
      dockerfile: docker/front/Dockerfile
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - ../:/app
    restart: unless-stopped
    tty: true
